#!/usr/bin/env -S uv run -s
# this_file: scripts/gen_cli_docs.py
"""Generate src_docs/md/8-toolkit/cli.md from the ``localizzy … --help`` output of every command.

The command list comes from ``vexy_localizzy.cli.COMMANDS``, so new commands
appear without editing this script. Help is rendered in-process by Fire, which
writes plain text to stderr (without a pager) when it is not a terminal. ``--check`` exits 1 when
src_docs/md/8-toolkit/cli.md is stale; tests/test_docs_cli.py runs the same comparison.

Usage:
    uv run scripts/gen_cli_docs.py          # rewrite src_docs/md/8-toolkit/cli.md
    uv run scripts/gen_cli_docs.py --check  # verify only
"""

import contextlib
import io
import re
import sys
from pathlib import Path

import fire

from vexy_localizzy.cli import COMMANDS

DOC = Path(__file__).resolve().parent.parent / "src_docs" / "md" / "8-toolkit" / "cli.md"
ANSI = re.compile(r"\x1b\[[0-9;]*m")
HEADER = """---
this_file: src_docs/md/8-toolkit/cli.md
---
# Command-line reference

Generated by `scripts/gen_cli_docs.py` from `localizzy … --help`; do not edit by
hand. Fire accepts `--flag value`, `--flag=value` and, for booleans,
`--noflag`. List flags take comma-separated values.
"""


def command_paths(tree: dict, prefix: tuple[str, ...] = ()) -> list[tuple[str, ...]]:
    """Every group and command path in the Fire command tree, depth first."""
    paths: list[tuple[str, ...]] = []
    for name, value in tree.items():
        path = (*prefix, name)
        paths.append(path)
        if isinstance(value, dict):
            paths.extend(command_paths(value, path))
    return paths


def help_text(path: tuple[str, ...]) -> str:
    """Fire's help for one command path as plain text."""
    err = io.StringIO()
    with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(err):
        with contextlib.suppress(SystemExit):
            fire.Fire(COMMANDS, command=[*path, "--help"], name="localizzy")
    lines = ANSI.sub("", err.getvalue()).strip().splitlines()
    if lines and lines[0].startswith("INFO: Showing help"):
        lines = lines[1:]
    text = "\n".join(line.rstrip() for line in lines).strip()
    if not text:
        raise RuntimeError(f"no help text for localizzy {' '.join(path)}")
    return text


def render() -> str:
    """The full src_docs/md/8-toolkit/cli.md text."""
    sections = [HEADER, "## localizzy\n", "```text", help_text(()), "```\n"]
    for path in command_paths(COMMANDS):
        sections += [
            f"## localizzy {' '.join(path)}\n",
            "```text",
            help_text(path),
            "```\n",
        ]
    return "\n".join(sections).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    text = render()
    if "--check" in args:
        current = DOC.read_text(encoding="utf-8") if DOC.exists() else ""
        if current != text:
            print(f"{DOC} is stale; run scripts/gen_cli_docs.py", file=sys.stderr)
            return 1
        return 0
    DOC.write_text(text, encoding="utf-8")
    print(f"wrote {DOC}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
